export const SAVE_POST = 'SAVE_POST'
export const GET_POSTS = 'GET_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const NEW_REPLY = 'NEW_REPLY'
export const REPLY_TXT_CHANGE = 'REPLY_TXT_CHANGE'
