 export const ActionTypes = {
    FETCH : 'FETCH_DATA',
    SUCCESS: 'FETCH_SUCCESS',
    FAILURE: 'FETCH_FAILURE',
    NEW_POST: 'ADD_NEW_POST',
    POST_TXT_CHANGE: 'NEW_POST_TXT_CHANGE',
    CLR_POST_TXT: 'CLR_POST_TXT',
    REPLY_TXT_CHANGE: 'REPLY_POST_TXT_CHANGE_HANDLER',
    NEW_REPLY: 'ADD_REPLY_POST'

 }